# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.19.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.19.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/changbenson/Github/Optimisation_mineral_recovery

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/changbenson/Github/Optimisation_mineral_recovery

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.19.4/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.19.4/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.19.4/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.19.4/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.19.4/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.19.4/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.19.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.19.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Only default component available"
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/changbenson/Github/acse-4-gormanium-rush-cuprite/CMakeFiles /Users/changbenson/Github/acse-4-gormanium-rush-cuprite//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/changbenson/Github/acse-4-gormanium-rush-cuprite/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test2

# Build rule for target.
test2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test2
.PHONY : test2

# fast build rule for target.
test2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/build
.PHONY : test2/fast

#=============================================================================
# Target rules for targets named test1

# Build rule for target.
test1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test1
.PHONY : test1

# fast build rule for target.
test1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/build
.PHONY : test1/fast

#=============================================================================
# Target rules for targets named test_GeneticAlgorithm

# Build rule for target.
test_GeneticAlgorithm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_GeneticAlgorithm
.PHONY : test_GeneticAlgorithm

# fast build rule for target.
test_GeneticAlgorithm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_GeneticAlgorithm.dir/build.make CMakeFiles/test_GeneticAlgorithm.dir/build
.PHONY : test_GeneticAlgorithm/fast

#=============================================================================
# Target rules for targets named mainP

# Build rule for target.
mainP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mainP
.PHONY : mainP

# fast build rule for target.
mainP/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainP.dir/build.make CMakeFiles/mainP.dir/build
.PHONY : mainP/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

src/CCircuit.o: src/CCircuit.cpp.o

.PHONY : src/CCircuit.o

# target to build an object file
src/CCircuit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/CCircuit.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/CCircuit.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_GeneticAlgorithm.dir/build.make CMakeFiles/test_GeneticAlgorithm.dir/src/CCircuit.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainP.dir/build.make CMakeFiles/mainP.dir/src/CCircuit.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/CCircuit.cpp.o
.PHONY : src/CCircuit.cpp.o

src/CCircuit.i: src/CCircuit.cpp.i

.PHONY : src/CCircuit.i

# target to preprocess a source file
src/CCircuit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/CCircuit.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/CCircuit.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_GeneticAlgorithm.dir/build.make CMakeFiles/test_GeneticAlgorithm.dir/src/CCircuit.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainP.dir/build.make CMakeFiles/mainP.dir/src/CCircuit.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/CCircuit.cpp.i
.PHONY : src/CCircuit.cpp.i

src/CCircuit.s: src/CCircuit.cpp.s

.PHONY : src/CCircuit.s

# target to generate assembly for a file
src/CCircuit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/CCircuit.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/CCircuit.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_GeneticAlgorithm.dir/build.make CMakeFiles/test_GeneticAlgorithm.dir/src/CCircuit.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainP.dir/build.make CMakeFiles/mainP.dir/src/CCircuit.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/CCircuit.cpp.s
.PHONY : src/CCircuit.cpp.s

src/Evaluate_Circuit.o: src/Evaluate_Circuit.cpp.o

.PHONY : src/Evaluate_Circuit.o

# target to build an object file
src/Evaluate_Circuit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/Evaluate_Circuit.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_GeneticAlgorithm.dir/build.make CMakeFiles/test_GeneticAlgorithm.dir/src/Evaluate_Circuit.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainP.dir/build.make CMakeFiles/mainP.dir/src/Evaluate_Circuit.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Evaluate_Circuit.cpp.o
.PHONY : src/Evaluate_Circuit.cpp.o

src/Evaluate_Circuit.i: src/Evaluate_Circuit.cpp.i

.PHONY : src/Evaluate_Circuit.i

# target to preprocess a source file
src/Evaluate_Circuit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/Evaluate_Circuit.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_GeneticAlgorithm.dir/build.make CMakeFiles/test_GeneticAlgorithm.dir/src/Evaluate_Circuit.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainP.dir/build.make CMakeFiles/mainP.dir/src/Evaluate_Circuit.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Evaluate_Circuit.cpp.i
.PHONY : src/Evaluate_Circuit.cpp.i

src/Evaluate_Circuit.s: src/Evaluate_Circuit.cpp.s

.PHONY : src/Evaluate_Circuit.s

# target to generate assembly for a file
src/Evaluate_Circuit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/Evaluate_Circuit.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_GeneticAlgorithm.dir/build.make CMakeFiles/test_GeneticAlgorithm.dir/src/Evaluate_Circuit.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainP.dir/build.make CMakeFiles/mainP.dir/src/Evaluate_Circuit.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Evaluate_Circuit.cpp.s
.PHONY : src/Evaluate_Circuit.cpp.s

src/Genetic_Algorithm.o: src/Genetic_Algorithm.cpp.o

.PHONY : src/Genetic_Algorithm.o

# target to build an object file
src/Genetic_Algorithm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/Genetic_Algorithm.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_GeneticAlgorithm.dir/build.make CMakeFiles/test_GeneticAlgorithm.dir/src/Genetic_Algorithm.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainP.dir/build.make CMakeFiles/mainP.dir/src/Genetic_Algorithm.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Genetic_Algorithm.cpp.o
.PHONY : src/Genetic_Algorithm.cpp.o

src/Genetic_Algorithm.i: src/Genetic_Algorithm.cpp.i

.PHONY : src/Genetic_Algorithm.i

# target to preprocess a source file
src/Genetic_Algorithm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/Genetic_Algorithm.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_GeneticAlgorithm.dir/build.make CMakeFiles/test_GeneticAlgorithm.dir/src/Genetic_Algorithm.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainP.dir/build.make CMakeFiles/mainP.dir/src/Genetic_Algorithm.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Genetic_Algorithm.cpp.i
.PHONY : src/Genetic_Algorithm.cpp.i

src/Genetic_Algorithm.s: src/Genetic_Algorithm.cpp.s

.PHONY : src/Genetic_Algorithm.s

# target to generate assembly for a file
src/Genetic_Algorithm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/Genetic_Algorithm.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_GeneticAlgorithm.dir/build.make CMakeFiles/test_GeneticAlgorithm.dir/src/Genetic_Algorithm.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainP.dir/build.make CMakeFiles/mainP.dir/src/Genetic_Algorithm.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Genetic_Algorithm.cpp.s
.PHONY : src/Genetic_Algorithm.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mainP.o: src/mainP.cpp.o

.PHONY : src/mainP.o

# target to build an object file
src/mainP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainP.dir/build.make CMakeFiles/mainP.dir/src/mainP.cpp.o
.PHONY : src/mainP.cpp.o

src/mainP.i: src/mainP.cpp.i

.PHONY : src/mainP.i

# target to preprocess a source file
src/mainP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainP.dir/build.make CMakeFiles/mainP.dir/src/mainP.cpp.i
.PHONY : src/mainP.cpp.i

src/mainP.s: src/mainP.cpp.s

.PHONY : src/mainP.s

# target to generate assembly for a file
src/mainP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainP.dir/build.make CMakeFiles/mainP.dir/src/mainP.cpp.s
.PHONY : src/mainP.cpp.s

tests/test1.o: tests/test1.cpp.o

.PHONY : tests/test1.o

# target to build an object file
tests/test1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/tests/test1.cpp.o
.PHONY : tests/test1.cpp.o

tests/test1.i: tests/test1.cpp.i

.PHONY : tests/test1.i

# target to preprocess a source file
tests/test1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/tests/test1.cpp.i
.PHONY : tests/test1.cpp.i

tests/test1.s: tests/test1.cpp.s

.PHONY : tests/test1.s

# target to generate assembly for a file
tests/test1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/tests/test1.cpp.s
.PHONY : tests/test1.cpp.s

tests/test2.o: tests/test2.cpp.o

.PHONY : tests/test2.o

# target to build an object file
tests/test2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/tests/test2.cpp.o
.PHONY : tests/test2.cpp.o

tests/test2.i: tests/test2.cpp.i

.PHONY : tests/test2.i

# target to preprocess a source file
tests/test2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/tests/test2.cpp.i
.PHONY : tests/test2.cpp.i

tests/test2.s: tests/test2.cpp.s

.PHONY : tests/test2.s

# target to generate assembly for a file
tests/test2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/tests/test2.cpp.s
.PHONY : tests/test2.cpp.s

tests/test_GeneticAlgorithm.o: tests/test_GeneticAlgorithm.cpp.o

.PHONY : tests/test_GeneticAlgorithm.o

# target to build an object file
tests/test_GeneticAlgorithm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_GeneticAlgorithm.dir/build.make CMakeFiles/test_GeneticAlgorithm.dir/tests/test_GeneticAlgorithm.cpp.o
.PHONY : tests/test_GeneticAlgorithm.cpp.o

tests/test_GeneticAlgorithm.i: tests/test_GeneticAlgorithm.cpp.i

.PHONY : tests/test_GeneticAlgorithm.i

# target to preprocess a source file
tests/test_GeneticAlgorithm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_GeneticAlgorithm.dir/build.make CMakeFiles/test_GeneticAlgorithm.dir/tests/test_GeneticAlgorithm.cpp.i
.PHONY : tests/test_GeneticAlgorithm.cpp.i

tests/test_GeneticAlgorithm.s: tests/test_GeneticAlgorithm.cpp.s

.PHONY : tests/test_GeneticAlgorithm.s

# target to generate assembly for a file
tests/test_GeneticAlgorithm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_GeneticAlgorithm.dir/build.make CMakeFiles/test_GeneticAlgorithm.dir/tests/test_GeneticAlgorithm.cpp.s
.PHONY : tests/test_GeneticAlgorithm.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... mainP"
	@echo "... test1"
	@echo "... test2"
	@echo "... test_GeneticAlgorithm"
	@echo "... src/CCircuit.o"
	@echo "... src/CCircuit.i"
	@echo "... src/CCircuit.s"
	@echo "... src/Evaluate_Circuit.o"
	@echo "... src/Evaluate_Circuit.i"
	@echo "... src/Evaluate_Circuit.s"
	@echo "... src/Genetic_Algorithm.o"
	@echo "... src/Genetic_Algorithm.i"
	@echo "... src/Genetic_Algorithm.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mainP.o"
	@echo "... src/mainP.i"
	@echo "... src/mainP.s"
	@echo "... tests/test1.o"
	@echo "... tests/test1.i"
	@echo "... tests/test1.s"
	@echo "... tests/test2.o"
	@echo "... tests/test2.i"
	@echo "... tests/test2.s"
	@echo "... tests/test_GeneticAlgorithm.o"
	@echo "... tests/test_GeneticAlgorithm.i"
	@echo "... tests/test_GeneticAlgorithm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

